name: CI macos

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-macos-clang:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: make CC=clang clean all

  build-macos-gcc:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make 
      run: make CC=gcc clean all
